### PR TITLE
RVS Documentation

### PR DESCRIPTION
**Pull request by samjwu**
Moved documentation from doc/ to docs/
- doc/mansrc/rvs.md > docs/cli.md

Point CMakeLists.txt and DoxyMan1 to docs/ folder

### CODE REVIEW

**Comment by saadrahim** [comment]
Is there CI available for this project?

**Comment by jkottiku** [comment]
> Is there CI available for this project?

**Comment by jkottiku** [comment]
> Is there CI available for this project?

Yes, under http://rocm-ci.amd.com/view/compute/job/compute-rocm-dkms-npi-hipclang there is job **compute-parallel-build-stage2libs** were RVS gets build as part CI.

**Review by manoj-freyr — APPROVED** [review]
looks good

**Pull request merged**
