### PR TITLE
Add Read the Docs configs to RVS

### PR DESCRIPTION
**Pull request by samjwu**
standardize .md doc files for sphinx

Rationale:
 - https://github.com/RadeonOpenCompute/rocm-docs-core#purpose

Preview: https://advanced-micro-devices-rocmvalidationsuite--588.com.readthedocs.build/en/588/index.html

### CODE REVIEW

**Comment by samjwu** [comment]
Will set ready for review when webhook/integrations for RTD is set up. Will paste link to site preview here.

**Comment by samjwu** [comment]
Docs Site Preview: https://advanced-micro-devices-rocmvalidationsuite--588.com.readthedocs.build/en/588/index.html

**Comment by saadrahim** [comment]
I would get the dependabot in and ask the team to review.

**Review by jkottiku — APPROVED** [review]

**Comment by jkottiku** [comment]
@samjwu @saadrahim Any updates/edits in RVS documentation we just change in *.md files (index.md, README.md, features.md ...) in docs folder. Right ?

**Comment by samjwu** [comment]
> @samjwu @saadrahim Any updates/edits in RVS documentation we just change in *.md files (index.md, README.md, features.md ...) in docs folder. Right ?

That's correct. For adding new pages, just create the new file and add it to `docs/.sphinx/_toc.yml.in`

**Review by manoj-freyr — APPROVED** [review]
looks good

**Pull request merged**
